### PR TITLE
Add variant "cuda" to configure libfabric with cuda support.

### PR DESCRIPTION
**Pull request by vchoi-hdfgroup**

### CODE REVIEW

**Comment by mdorier** [comment]
There seems to be a "cuda" package in spack. I think the variant should just be a binary variant (`+cuda/~cuda`) and there should probably be a `depends_on("cuda", when="+cuda")` instead of a hard-coded path.

**Comment by vchoi-hdfgroup** [comment]
Thank you for the info about the cuda spack package.  I will make modifications accordingly.

**Comment by vchoi-hdfgroup** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mdorier** [comment]
You still need to add `--with-cuda=...` with the path to cuda if `"+cuda"` is in `self.spec`.

**Comment by carns** [comment]
This looks good to me with the latest commits.

Can the `cudatoolkit-standalone` module on Polaris be used as an external package in the spack configuration to satisfy this dependency?  Or does spack build its own?

I imagine either way is Ok as long as the benchmark works as a result, I'm just curious what the configuration looks like.

**Comment by carns** [comment]
Also I suspect that the CLA assistant is failing because the actual commits in this pull request are associated with a thetagpu/alcf email address of some sort rather than the email address associated with your github account.  That's Ok, though, we know it's you :)

**Comment by carns** [comment]
Thanks, I see the example of the external cuda dep in https://github.com/mochi-hpc-experiments/platform-configurations/pull/20 now.

**Pull request merged**
